services:
  - type: web
    name: realtime-orders-notify
    env: node
    plan: free
    installCommand: npm ci --include=dev
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production